"""vacancies and questions

Revision ID: a9e57ad3da88
Revises: 3a71b5cdeeba
Create Date: 2026-09-03 13:04:57.580163
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a9e57ad3da88"
down_revision: str | None = "3a71b5cdeeba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("requirements", sa.Text(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "archived",
                name="vacancy_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rubric", sa.JSON(), nullable=False),
        sa.Column("intro_text", sa.Text(), nullable=False),
        sa.Column("prep_seconds", sa.Integer(), nullable=False),
        sa.Column("max_answer_seconds", sa.Integer(), nullable=False),
        sa.Column("retakes_allowed", sa.Integer(), nullable=False),
        sa.Column("practice_question_enabled", sa.Boolean(), nullable=False),
        sa.Column("followups_enabled", sa.Boolean(), nullable=False),
        sa.Column("followups_max", sa.Integer(), nullable=False),
        sa.Column("tts_enabled", sa.Boolean(), nullable=False),
        sa.Column("voice", sa.String(length=64), nullable=False),
        sa.Column("invitation_days", sa.Integer(), nullable=False),
        sa.Column(
            "candidate_feedback_mode",
            sa.Enum(
                "off",
                "after_decision",
                "auto_after_days",
                name="candidate_feedback_mode",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("candidate_feedback_after_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vacancies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vacancies_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_vacancies_status"), ["status"], unique=False)

    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vacancy_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("video", "code", name="question_kind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("expected_points", sa.JSON(), nullable=False),
        sa.Column("competency_ids", sa.JSON(), nullable=False),
        sa.Column("allows_followup", sa.Boolean(), nullable=False),
        sa.Column("prep_seconds", sa.Integer(), nullable=True),
        sa.Column("max_answer_seconds", sa.Integer(), nullable=True),
        sa.Column("retakes_allowed", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["vacancy_id"], ["vacancies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vacancy_id", "position", name="uq_question_position"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_questions_vacancy_id"), ["vacancy_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_vacancy_id"))

    op.drop_table("questions")
    with op.batch_alter_table("vacancies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vacancies_status"))
        batch_op.drop_index(batch_op.f("ix_vacancies_organization_id"))

    op.drop_table("vacancies")
    # ### end Alembic commands ###
