"""evaluations

Revision ID: d7861cfffbf1
Revises: c100757fb1a1
Create Date: 2026-09-03 14:25:59.836274
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d7861cfffbf1"
down_revision: str | None = "c100757fb1a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "done", "failed", name="evaluation_status", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("fit_score", sa.Float(), nullable=True),
        sa.Column("recommendation", sa.String(length=16), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("candidate_feedback", sa.JSON(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evaluations_interview_id"), ["interview_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluations_interview_id"))

    op.drop_table("evaluations")
    # ### end Alembic commands ###
