"""candidates interviews consents emails

Revision ID: 26af6f4296b2
Revises: d233f24231da
Create Date: 2026-09-03 13:21:55.152973
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "26af6f4296b2"
down_revision: str | None = "d233f24231da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "bulk",
                "hh",
                "huntflow",
                "api",
                name="candidate_source",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("resume_key", sa.String(length=512), nullable=True),
        sa.Column("resume_filename", sa.String(length=255), nullable=True),
        sa.Column("resume_text", sa.Text(), nullable=True),
        sa.Column("external_ref", sa.String(length=128), nullable=True),
        sa.Column("newsletter_opt_in", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "email", name="uq_candidate_org_email"),
    )
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candidates_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_candidates_external_ref"), ["external_ref"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_candidates_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "interviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("vacancy_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "invited",
                "opened",
                "consented",
                "in_progress",
                "completed",
                "processing",
                "evaluated",
                "reviewed",
                "advanced",
                "rejected",
                "expired",
                "cancelled",
                name="interview_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_full_name", sa.String(length=255), nullable=True),
        sa.Column("consent_email", sa.String(length=320), nullable=True),
        sa.Column("newsletter_opt_in", sa.Boolean(), nullable=False),
        sa.Column("consent_ip", sa.String(length=64), nullable=True),
        sa.Column("consent_user_agent", sa.String(length=512), nullable=True),
        sa.Column("question_snapshot", sa.JSON(), nullable=True),
        sa.Column("settings_snapshot", sa.JSON(), nullable=True),
        sa.Column("current_question_index", sa.Integer(), nullable=False),
        sa.Column("client_info", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("external_ref", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["decided_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["invited_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vacancy_id"], ["vacancies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interviews_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interviews_external_ref"), ["external_ref"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interviews_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_interviews_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_interviews_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_interviews_vacancy_id"), ["vacancy_id"], unique=False)

    op.create_table(
        "consent_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("document_hash", sa.String(length=64), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consent_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consent_records_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_consent_records_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_consent_records_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "email_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("interview_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("to_email", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "sent", "failed", name="email_status", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_messages_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_email_messages_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_email_messages_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_messages_status"))
        batch_op.drop_index(batch_op.f("ix_email_messages_organization_id"))
        batch_op.drop_index(batch_op.f("ix_email_messages_interview_id"))

    op.drop_table("email_messages")
    with op.batch_alter_table("consent_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consent_records_organization_id"))
        batch_op.drop_index(batch_op.f("ix_consent_records_interview_id"))
        batch_op.drop_index(batch_op.f("ix_consent_records_candidate_id"))

    op.drop_table("consent_records")
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interviews_vacancy_id"))
        batch_op.drop_index(batch_op.f("ix_interviews_token_hash"))
        batch_op.drop_index(batch_op.f("ix_interviews_status"))
        batch_op.drop_index(batch_op.f("ix_interviews_organization_id"))
        batch_op.drop_index(batch_op.f("ix_interviews_external_ref"))
        batch_op.drop_index(batch_op.f("ix_interviews_candidate_id"))

    op.drop_table("interviews")
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidates_organization_id"))
        batch_op.drop_index(batch_op.f("ix_candidates_external_ref"))
        batch_op.drop_index(batch_op.f("ix_candidates_email"))

    op.drop_table("candidates")
    # ### end Alembic commands ###
