"""reminder and unsubscribe timestamps

Revision ID: 6d2ce238cdd0
Revises: 7b30751847ce
Create Date: 2026-09-04 02:44:43.596492
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6d2ce238cdd0"
down_revision: str | None = "7b30751847ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.drop_column("reminder_sent_at")

    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.drop_column("unsubscribed_at")

    # ### end Alembic commands ###
