"""answers and interview events

Revision ID: 2e633b2a0281
Revises: 26af6f4296b2
Create Date: 2026-09-03 13:38:58.756448
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2e633b2a0281"
down_revision: str | None = "26af6f4296b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("question_index", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.String(length=64), nullable=True),
        sa.Column("parent_answer_id", sa.Uuid(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "recording",
                "uploaded",
                "processing",
                "done",
                "failed",
                "abandoned",
                name="answer_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("media_key", sa.String(length=512), nullable=True),
        sa.Column("media_content_type", sa.String(length=128), nullable=True),
        sa.Column("media_size", sa.BigInteger(), nullable=False),
        sa.Column("upload_offset", sa.BigInteger(), nullable=False),
        sa.Column("audio_key", sa.String(length=512), nullable=True),
        sa.Column("recording_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_chunk_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_chunk_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recording_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("client_duration_ms", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("transcript_text", sa.Text(), nullable=True),
        sa.Column("transcript_segments", sa.JSON(), nullable=True),
        sa.Column("transcript_language", sa.String(length=16), nullable=True),
        sa.Column("media_meta", sa.JSON(), nullable=False),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_answer_id"], ["answers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interview_id", "question_index", "attempt", name="uq_answer_attempt"),
    )
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_answers_interview_id"), ["interview_id"], unique=False)
        batch_op.create_index(
            "ix_answers_interview_question", ["interview_id", "question_index"], unique=False
        )

    op.create_table(
        "interview_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=True),
        sa.Column("question_index", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("at_client_ms", sa.BigInteger(), nullable=True),
        sa.Column("at_server", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["answer_id"], ["answers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interview_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interview_events_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(
            "ix_interview_events_interview_kind", ["interview_id", "kind"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview_events", schema=None) as batch_op:
        batch_op.drop_index("ix_interview_events_interview_kind")
        batch_op.drop_index(batch_op.f("ix_interview_events_interview_id"))

    op.drop_table("interview_events")
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_index("ix_answers_interview_question")
        batch_op.drop_index(batch_op.f("ix_answers_interview_id"))

    op.drop_table("answers")
    # ### end Alembic commands ###
