"""hh integration

Revision ID: 7b30751847ce
Revises: c100757fb1a1
Create Date: 2026-09-03 18:50:56.578321
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7b30751847ce"
down_revision: str | None = "23d76f688b0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hh_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("employer_id", sa.String(length=64), nullable=False),
        sa.Column("employer_name", sa.String(length=255), nullable=False),
        sa.Column("hh_user_id", sa.String(length=64), nullable=False),
        sa.Column("manager_account_id", sa.String(length=64), nullable=True),
        sa.Column("access_token_enc", sa.Text(), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "connected",
                "error",
                "disconnected",
                name="hh_connection_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("webhook_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("webhook_secret_enc", sa.Text(), nullable=False),
        sa.Column("connected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connected_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", name="uq_hh_connection_org"),
    )
    with op.batch_alter_table("hh_connections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hh_connections_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hh_connections_webhook_secret_hash"),
            ["webhook_secret_hash"],
            unique=True,
        )

    op.create_table(
        "hh_vacancy_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("vacancy_id", sa.Uuid(), nullable=False),
        sa.Column("hh_vacancy_id", sa.String(length=64), nullable=False),
        sa.Column("hh_title", sa.String(length=255), nullable=False),
        sa.Column("hh_url", sa.String(length=512), nullable=False),
        sa.Column("dialog", sa.JSON(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["hh_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vacancy_id"], ["vacancies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "hh_vacancy_id", name="uq_hh_vacancy_link"),
    )
    with op.batch_alter_table("hh_vacancy_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hh_vacancy_links_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hh_vacancy_links_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hh_vacancy_links_vacancy_id"), ["vacancy_id"], unique=False
        )

    op.create_table(
        "hh_negotiations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("vacancy_link_id", sa.Uuid(), nullable=False),
        sa.Column("negotiation_id", sa.String(length=64), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("resume_id", sa.String(length=128), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "new",
                "greeting_sent",
                "awaiting_slot",
                "link_sent",
                "done",
                "declined",
                "needs_recruiter",
                name="hh_dialog_state",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("chosen_date", sa.Date(), nullable=True),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("last_hh_message_id", sa.String(length=64), nullable=True),
        sa.Column("clarify_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["connection_id"], ["hh_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vacancy_link_id"], ["hh_vacancy_links.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "negotiation_id", name="uq_hh_negotiation"),
    )
    with op.batch_alter_table("hh_negotiations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hh_negotiations_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hh_negotiations_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hh_negotiations_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hh_negotiations_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_hh_negotiations_state"), ["state"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_hh_negotiations_vacancy_link_id"), ["vacancy_link_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hh_negotiations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hh_negotiations_vacancy_link_id"))
        batch_op.drop_index(batch_op.f("ix_hh_negotiations_state"))
        batch_op.drop_index(batch_op.f("ix_hh_negotiations_organization_id"))
        batch_op.drop_index(batch_op.f("ix_hh_negotiations_interview_id"))
        batch_op.drop_index(batch_op.f("ix_hh_negotiations_connection_id"))
        batch_op.drop_index(batch_op.f("ix_hh_negotiations_candidate_id"))

    op.drop_table("hh_negotiations")
    with op.batch_alter_table("hh_vacancy_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hh_vacancy_links_vacancy_id"))
        batch_op.drop_index(batch_op.f("ix_hh_vacancy_links_organization_id"))
        batch_op.drop_index(batch_op.f("ix_hh_vacancy_links_connection_id"))

    op.drop_table("hh_vacancy_links")
    with op.batch_alter_table("hh_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hh_connections_webhook_secret_hash"))
        batch_op.drop_index(batch_op.f("ix_hh_connections_organization_id"))

    op.drop_table("hh_connections")
    # ### end Alembic commands ###
