"""answer code submission

Revision ID: 7751205fe20c
Revises: 2e50dfb96cb0
Create Date: 2026-09-03 18:41:42.007883
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7751205fe20c"
down_revision: str | None = "23d76f688b0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code_submission", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_column("code_submission")

    # ### end Alembic commands ###
