"""integrity reviews

Revision ID: 121fcfc40621
Revises: b78ecd8d46b5
Create Date: 2026-09-04 02:57:42.800377
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "121fcfc40621"
down_revision: str | None = "6d2ce238cdd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrity_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("question_index", sa.Integer(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "confirmed",
                "false_positive",
                name="integrity_verdict",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_label", sa.String(length=255), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "interview_id", "code", "question_index", name="uq_integrity_review_observation"
        ),
    )
    with op.batch_alter_table("integrity_reviews", schema=None) as batch_op:
        batch_op.create_index("ix_integrity_reviews_interview", ["interview_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_integrity_reviews_organization_id"), ["organization_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("integrity_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_integrity_reviews_organization_id"))
        batch_op.drop_index("ix_integrity_reviews_interview")

    op.drop_table("integrity_reviews")
    # ### end Alembic commands ###
