"""huntflow integration

Revision ID: b78ecd8d46b5
Revises: c100757fb1a1
Create Date: 2026-09-03 18:42:15.896113
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b78ecd8d46b5"
down_revision: str | None = "7751205fe20c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "huntflow_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("real", "fake", name="huntflow_mode", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("token_encrypted", sa.Text(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("account_name", sa.String(length=255), nullable=True),
        sa.Column("owner_name", sa.String(length=255), nullable=True),
        sa.Column("owner_email", sa.String(length=320), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "needs_account",
                "error",
                name="huntflow_connection_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connected_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("huntflow_connections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_huntflow_connections_organization_id"), ["organization_id"], unique=True
        )

    op.create_table(
        "huntflow_vacancy_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("vacancy_id", sa.Uuid(), nullable=False),
        sa.Column("huntflow_vacancy_id", sa.Integer(), nullable=False),
        sa.Column("huntflow_vacancy_title", sa.String(length=255), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("status_name", sa.String(length=255), nullable=True),
        sa.Column("last_imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["huntflow_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vacancy_id"], ["vacancies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "vacancy_id", name="uq_huntflow_link_vacancy"),
    )
    with op.batch_alter_table("huntflow_vacancy_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_huntflow_vacancy_links_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_huntflow_vacancy_links_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_huntflow_vacancy_links_vacancy_id"), ["vacancy_id"], unique=False
        )

    op.create_table(
        "huntflow_applicants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=True),
        sa.Column("huntflow_applicant_id", sa.Integer(), nullable=True),
        sa.Column("huntflow_vacancy_id", sa.Integer(), nullable=True),
        sa.Column("huntflow_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "linked",
                "queued",
                "pushing",
                "pushed",
                "error",
                name="huntflow_push_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("last_pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("pushed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("report_share_id", sa.Uuid(), nullable=True),
        sa.Column("report_share_url", sa.Text(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["connection_id"], ["huntflow_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pushed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["report_share_id"], ["report_shares.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "candidate_id", name="uq_huntflow_applicant_candidate"
        ),
    )
    with op.batch_alter_table("huntflow_applicants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_huntflow_applicants_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_huntflow_applicants_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_huntflow_applicants_huntflow_applicant_id"),
            ["huntflow_applicant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_huntflow_applicants_organization_id"), ["organization_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("huntflow_applicants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_huntflow_applicants_organization_id"))
        batch_op.drop_index(batch_op.f("ix_huntflow_applicants_huntflow_applicant_id"))
        batch_op.drop_index(batch_op.f("ix_huntflow_applicants_connection_id"))
        batch_op.drop_index(batch_op.f("ix_huntflow_applicants_candidate_id"))

    op.drop_table("huntflow_applicants")
    with op.batch_alter_table("huntflow_vacancy_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_huntflow_vacancy_links_vacancy_id"))
        batch_op.drop_index(batch_op.f("ix_huntflow_vacancy_links_organization_id"))
        batch_op.drop_index(batch_op.f("ix_huntflow_vacancy_links_connection_id"))

    op.drop_table("huntflow_vacancy_links")
    with op.batch_alter_table("huntflow_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_huntflow_connections_organization_id"))

    op.drop_table("huntflow_connections")
    # ### end Alembic commands ###
