"""assistant threads and messages

Revision ID: 15d71ef2518e
Revises: 2e50dfb96cb0
Create Date: 2026-09-03 18:41:25.208621
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "15d71ef2518e"
down_revision: str | None = "2e50dfb96cb0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_threads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("page_path", sa.String(length=512), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assistant_threads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assistant_threads_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_assistant_threads_user_id"), ["user_id"], unique=False)

    op.create_table(
        "assistant_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user",
                "assistant",
                "tool",
                name="assistant_message_role",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["assistant_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assistant_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assistant_messages_thread_id"), ["thread_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assistant_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assistant_messages_thread_id"))

    op.drop_table("assistant_messages")
    with op.batch_alter_table("assistant_threads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assistant_threads_user_id"))
        batch_op.drop_index(batch_op.f("ix_assistant_threads_organization_id"))

    op.drop_table("assistant_threads")
    # ### end Alembic commands ###
