"""review notes and report shares

Revision ID: c100757fb1a1
Revises: 2e633b2a0281
Create Date: 2026-09-03 13:51:45.468778
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c100757fb1a1"
down_revision: str | None = "2e633b2a0281"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_shares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("include_integrity", sa.Boolean(), nullable=False),
        sa.Column("allow_download", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("last_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report_shares", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_shares_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_report_shares_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_report_shares_token_hash"), ["token_hash"], unique=True
        )

    op.create_table(
        "report_views",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("share_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("what", sa.String(length=32), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["share_id"], ["report_shares.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report_views", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_views_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_report_views_share_id"), ["share_id"], unique=False)

    op.create_table(
        "review_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("author_label", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=True),
        sa.Column("at_s", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["answer_id"], ["answers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_notes_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_notes_organization_id"), ["organization_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_notes_organization_id"))
        batch_op.drop_index(batch_op.f("ix_review_notes_interview_id"))

    op.drop_table("review_notes")
    with op.batch_alter_table("report_views", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_views_share_id"))
        batch_op.drop_index(batch_op.f("ix_report_views_interview_id"))

    op.drop_table("report_views")
    with op.batch_alter_table("report_shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_shares_token_hash"))
        batch_op.drop_index(batch_op.f("ix_report_shares_organization_id"))
        batch_op.drop_index(batch_op.f("ix_report_shares_interview_id"))

    op.drop_table("report_shares")
    # ### end Alembic commands ###
